### PR TITLE
add travis.yml

### PR DESCRIPTION
**Pull request by mvo5**
This is a tiny branch that just adds basic `.travis.yml` integration.

 Before you merge you need to flick the repository switch on in travis-ci.org under your account. Then you should see the travis build and the travis banner in your readme :)

Note that the build fails right now, which I can also reproduce locally. I bisected it and it starts breaking with commit 5269cf26ba096845b4a62901b7b1ebb49781177a on ubuntu. This might be a linux specific issue but before digging into it I wanted to add thetravis support first in order to avoid this kind of issue in the future.

Thanks for your consideration!

### CODE REVIEW

**Comment by mvo5** [comment]
ping?

**Comment by mvo5** [comment]
Sorry, this was a bit rude. I meant to ask if there is anything that I can help to move this forward. Or if there is no interest in this (which is fine!). If the later this (and the subsequent pull-request) can just be closed.

**Comment by xiam** [comment]
Don't worry! and thanks for pinging, I am the only one acting rude here by not taking any action on a good contribution and I'm sorry for that. I think I really need to transfer this project to better hands to be able to let it move forward, this is not the first time that I fail to check what's going on here. Your past contributions were awesome, not sure if you have the time but would you like to have write/admin access to it? that would really help the project. We could also move it to a different organization, I think the org name "gosexy" wasn't the best choice.

**Comment by xiam** [comment]
Looks good, by the way :). Thanks!

**Pull request merged**
